<?php
include("/db_connection.php");
$studentId=$_POST['student_id']
$query="SELECT * FROM students WHERE student_id='$studentId'";
$studentData="";
$result=mysqli_query($conn,$query);
if($result)
{
    $information=mysqli_fetch_assoc($result);
    $studentData.="
        <tr>
                <td>".htmlspecialchars($information['name'])."</td>
                <td>".htmlspecialchars($information['class'])."</td>
                <td>".htmlspecialchars($information['grade_unit1'])."</td>
                <td>".htmlspecialchars($information['grade_unit2'])."</td>
                <td>".htmlspecialchars($information['grade_unit3'])."</td>
                <td>".htmlspecialchars($information['final_grade'])."</td>
        </tr>
    ";
}
?>